1. Create and inspect an Array. Create a 1D numpy array containing integers from 10 to 50 (inclusive) with a step of 5. Print its shape , size and data type.


In [ ]:
import numpy as np
arr = np.arange(10,51,5)
print("Array:",arr)
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)

Array: [10 15 20 25 30 35 40 45 50]
Shape: (9,)
Size: 9
Data type: int64


2. Generate a matrix with random values. Generate a 4x5 NumPy array with random integers between 1 and 100. Find the maximum and minimum values along with their indices.

In [ ]:
import numpy as np
arr = np.random.randint(1, 101, size=(4, 5))
print("Array:")
print(arr)
max_value = arr.max()
min_value = arr.min()
max_index = arr.argmax()
min_index = arr.argmin()
max_coords = np.unravel_index(max_index, arr.shape)
min_coords = np.unravel_index(min_index, arr.shape)
print(f"Maximum value: {max_value}")
print(f"Maximum coordinates: {max_coords}")
print(f"Minimum value: {min_value}")
print(f"Minimum coordinates: {min_coords}")


Array:
[[ 55  77 100  94  22]
 [ 58  54  53  86  71]
 [ 67  61  77  95  90]
 [ 71  92  28   2  64]]
Maximum value: 100
Maximum coordinates: (np.int64(0), np.int64(2))
Minimum value: 2
Minimum coordinates: (np.int64(3), np.int64(3))


3. Reshape an array. Create a 1D array of numbers from 1 to 24 , then reshape it into a 4x6 matrix. Extract the 2nd row and 3rd column.

In [ ]:
import numpy as np
arr = np.arange(1, 25)
matrix = arr.reshape(4, 6)
value = matrix[1, 2]
print(value)

9


4. Boolean Indexing. Given a NumPy array of 15 random integers between 0 and 50. Find all elements greater than 25 and replace them with -1.

In [ ]:
import numpy as np
arr = np.random.randint(0, 51, 15)
arr[arr > 25] = -1
print(arr)

[-1 -1 -1 -1 -1  1 -1 -1 21 -1 -1 12 -1 -1 -1]


5. Mathematical operations. Create two 1D NumPy arrays: a=[1,2,3,4,5] and b=[10,20,30,40,50]. Perform element-wise addition , subtraction , multiplication and division.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


6.Statistical computations. Generate a 5x5 matrix with random floats between 0 and 1. Compute the mean , median , variance and standard deviation.

In [ ]:
import numpy as np
matrix = np.random.rand(5, 5)
print(np.mean(matrix))
print(np.median(matrix))
print(np.var(matrix))
print(np.std(matrix))

0.5017483024285581
0.4906188545867003
0.08455493690614638
0.2907833160725463


7. import numpy as np

   A = np.array( [ [1,2] , [3,4] , [5,6] ] )

   B = np.array( [ [7,8,9] , [10,11,12] ] )

   print(A @ B)

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
print(A @ B)

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


8. Slice and modify. Create a 6x6 array of integers from 1 to 36. Extract the 3x3 sub-matrix from center and set all its values to 0.

In [ ]:
import numpy as np
arr = np.arange(1, 37).reshape(6, 6)
arr[1:4, 1:4] = 0
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  0  0  0 11 12]
 [13  0  0  0 17 18]
 [19  0  0  0 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


9. Use of np.where
   
   NumPy array with values [5 , 10 , 15 , 20 , 25].
   
   Replace all elements greater than 15 with 99 , otherwise replace with 0.

In [ ]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
result = np.where(arr > 15, 99, 0)
print(result)

[ 0  0  0 99 99]


10. Broadcasting Example . Create a 4x4 array with 10s. Subtract a 1D array [ 0 , 1 , 2 , 3 ] from each row using NumPy broadcasting.

In [ ]:

import numpy as np
arr = np.full((4, 4), 10)
arr -= np.array([0, 1, 2, 3])
print(arr)

[[10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]
 [10  9  8  7]]
